### ISSUE TITLE
ValueError: 'Reference' is not in list

### ISSUE THREAD

**Issue by flvinny** [AbdyyEee/PylibMS#1]
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\message\Touch\doit.py", line 22, in <module>
    msbt.write(writer)
  File "C:\Users\User\Desktop\message\Touch\Lib\site-packages\LMS\Message\MSBT.py", line 126, in write
    self.TXT2.write(writer, msbp)
  File "C:\Users\User\Desktop\message\Touch\Lib\site-packages\LMS\Message\TXT2.py", line 95, in write
    Tag_Utility.write_decoded_tag(message_writer, part, msbp)
  File "C:\Users\User\Desktop\message\Touch\Lib\site-packages\LMS\Message\Tags.py", line 185, in write_decoded_tag
    for group in structure].index(tag_info["group_name"])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'Reference' is not in list
```

This is my script, just reading a MSBT file and writing it back to a different file:
```py
from LMS.Message.MSBT import MSBT
from LMS.Project.MSBP import MSBP
from LMS.Stream.Reader import Reader
from LMS.Stream.Writer import Writer

with open('Touch.msbp', 'rb') as project:
  msbp = MSBP()
  reader = Reader(project.read())
  msbp.read(reader) 

with open('Touch_ScriptText.msbt', 'rb') as message:
  msbt = MSBT()
  reader = Reader(message.read())
  msbt.read(reader, msbp)
  
# Changes to the MSBT file would go here

with open('NEWTouch_ScriptText.msbt', 'rb+') as new_message:
  writer = Writer(b'')
  msbt.write(writer)
  new_message.write(writer.get_data())
```

I'm running Python 3.12.3 if that's of any help

**Comment by AbdyyEee** [comment]
The issue seems to be that you didn't provide an msbp in `msbt.write`. Since you read with an msbp, it must also be used to write the decoded tags. If there are any other issues let me know.

**Comment by flvinny** [comment]
Yeah, that was it 🤦 Thank you, will do!
